config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'

  namespace :admin do
    get '', to: 'home#index', as: '/' 

    resources :tickets
    resources :customers
    resources :activations
    resources :plates
    resources :penalties do
      get '/payment' => 'penalties#payment', as: :pay
    end
    resources :purchases
    resources :agents
    resources :penalty_payments, only: [:create, :destroy]

    authenticated :user do
      devise_scope :user do
        root to: 'admin/home#index', as: :root
      end
    end

    unauthenticated do
      devise_scope :user do
        root to: 'admin/sessions#new', as: :unauthenticated_root
      end
    end

    devise_for :users, controllers: {
      sessions: 'admin/sessions',
      registrations: 'admin/registrations',
      passwords: 'admin/passwords'
    }
  end

  namespace :api do
    namespace :v1 do
      resources :customers, only: [:index, :create, :show, :update, :destroy]
      resources :agents, only: [:index, :create, :show, :update, :destroy]
      resources :tickets, only: [:index, :create, :show, :update, :destroy]
      resources :activations, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get 'last_activation' => 'activations#last_activation', as: :last_activation
          get ':plate_code/last_activations' => 'activations#last_activations', as: :last_activations
          get ':customer_id' => 'activations#customer', as: :customer
        end
      end
      resources :penalties, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get '/plate/:plate_id' => 'penalties#plate', as: :plate
          get '/customer/' => 'penalties#customer', as: :customer
          get '/agent/' => 'penalties#agent', as: :agent
          post '/payment' => 'penalties#payment', as: :payment
        end
      end
      resources :purchases, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get '/customer/' => 'purchases#customer', as: :customer
        end
      end
      
      resources :plates, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get '/customer/' => 'plates#customer', as: :customer
        end
      end

      devise_scope :customer do
        resources :sessions, only: [:create]
        resources :registrations, only: [:create, :update]
      end

      devise_scope :agents do
        resources :sessions, only: [:create]
        resources :registrations, only: [:create, :update]
      end
    end
  end

  

end

app/models/activation.rb
class Activation < ActiveRecord::Base

	validates :customer_id, presence: true
	validates :ticket_id, presence: true

	belongs_to :ticket
	belongs_to :customer
	belongs_to :plate

	def remaining
		remaining = (((self.created_at - DateTime.now) / 60) + self.ticket.duration).to_i
		if remaining <= 0
			return 'Finalizado'
		else
			return "#{remaining} minutos"
		end
	end

	def percentage
		a = self.ticket.duration
		b = 100
		c = self.remaining_minutes
		d = (b*c)/a

		if d <= 0
			return 0
		else
			return d
		end
	end

	def remaining_minutes
		return (((self.created_at - DateTime.now) / 60) + self.ticket.duration).to_i
	end
end

app/controllers/admin/activations_controller.rb
class Admin::ActivationsController < Admin::AdminController
  before_action :set_activation, only: [:show, :edit, :update, :destroy]

  # GET /activations
  # GET /activations.json
  def index
    @activations = Activation.paginate(:page => params[:page])
  end

  # GET /activations/1
  # GET /activations/1.json
  def show
  end

  # GET /activations/new
  def new
    @activation = Activation.new
  end

  # GET /activations/1/edit
  def edit
  end

  # POST /activations
  # POST /activations.json
  def create
    @activation = Activation.new(activation_params)

    respond_to do |format|
      if @activation.save
        format.html { redirect_to [:admin, @activation], notice: 'Activation was successfully created.' }
        format.json { render :show, status: :created, location: @activation }
      else
        format.html { render :new }
        format.json { render json: @activation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activations/1
  # PATCH/PUT /activations/1.json
  def update
    respond_to do |format|
      if @activation.update(activation_params)
        format.html { redirect_to [:admin, @activation], notice: 'Activation was successfully updated.' }
        format.json { render :show, status: :ok, location: @activation }
      else
        format.html { render :edit }
        format.json { render json: @activation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activations/1
  # DELETE /activations/1.json
  def destroy
    @activation.destroy
    respond_to do |format|
      format.html { redirect_to admin_activations_url, notice: 'Activation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activation
      @activation = Activation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activation_params
      params.require(:activation).permit(:ticket_id, :customer_id, :plate_id)
    end
end

app/controllers/api/v1/activations_controller.rb
class Api::V1::ActivationsController < Api::V1::BaseController
  include ActiveHashRelation

  def index
    activations = Activation.paginate(:page => params[:page])

    activations = apply_filters(activations, params)

    render(
      json: ActiveModel::Serializer::CollectionSerializer.new(
        activations,
        serializer: Api::V1::ActivationSerializer,
        root: 'activations',
      )
    )
  end
  
  def show
    activation = Activation.find(params[:id])

    render json: Api::V1::ActivationSerializer.new(activation).to_json
  end

  def last_activation
    activation = @current_customer.activations ? @current_customer.activations.last : null
    # activation = Activation.where(params[:customer_id]).last

    if(activation)
      render json: Api::V1::ActivationSerializer.new(activation).to_json
    else
      render json: []
    end
  end

  # Only Agent
  def last_activations

    return invalid_user unless @current_agent

    plate = Plate.find_by(code: params[:plate_code])

    return api_error unless plate

    activations = plate.activations.order(id: :desc).last(3)

    # render json: activations

    render(
      json: ActiveModel::Serializer::CollectionSerializer.new(
        activations,
        serializer: Api::V1::ActivationSerializer,
        root: 'activations',
      )
    )
  end

  def customer
    activations = @current_customer.activations.order(id: :desc)

    render(
      json: ActiveModel::Serializer::CollectionSerializer.new(
        activations,
        serializer: Api::V1::ActivationSerializer,
        root: 'activations',
      )
    )
  end

  # POST /activations
  # POST /activations.json
  def create

    return invalid_user unless @current_customer

    @activation = Activation.new(activation_params)

    @activation.customer = @current_customer

    ticket = Ticket.find(@activation.ticket_id)
      return invalid_ticket unless ticket

    plate = Plate.find(@activation.plate_id)
      return invalid_plate unless plate

    if(@current_customer.cash < ticket.price)
      return not_enough_cash
    end

    if @activation.save
      newcash = @current_customer.cash - ticket.price

      @current_customer.cash = newcash

      @current_customer.save

      render json: Api::V1::ActivationSerializer.new(@activation).to_json, status: 200
    else
      render json: @ticket.errors, status: 422
    end
  end

  private

    def invalid_ticket
      warden.custom_failure!
      render(
        json: {:errors => ["Ticket não encontrado."]},
        status: 401
      )
    end

    def invalid_plate
      warden.custom_failure!
      render(
        json: {:errors => ["Placa não encontrada."]},
        status: 401
      )
    end

    def not_enough_cash
      warden.custom_failure!
      render(
        json: {:errors => ["Saldo insuficiente."]},
        status: 401
      )
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_activation
      @activation = Activation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activation_params
      params.require(:activation).permit(:ticket_id, :customer_id, :plate_id)
    end
end

app/helpers/activations_helper.rb
module ActivationsHelper
end

app/views/admin/activations/_form.html.haml
= simple_form_for([:admin, @activation]) do |f|
  = f.error_notification
  .row
    .col.s8.offset-s2.card-panel
      %fieldset.center
        %legend= @activation.new_record? ? 'Nova Ativação' : 'Editar Ativação'
        .input-field-2
          = f.association :ticket, :collection => Ticket.all.collect {|t| ["#{t.name} (#{number_to_currency(t.price, unit: 'R$ ', separator: ',', delimiter: '')})" , t.id]}
        .input-field-2
          = f.association :customer, :collection => Customer.all.collect {|c| [c.email, c.id]}
        .input-field-2
          = f.association :plate, :collection => Plate.all.collect {|p| [p.code, p.id]}

        = f.button :submit, input_html: {class: "btn waves-effect waves-light"}

        = link_to t("general.back"), :back, class: "btn white-text waves-effect waves-dark", title: t("general.back")

app/views/admin/activations/edit.html.haml
= render 'form'

app/views/admin/activations/index.html.haml
.row
  .card-panel.col.s12
    %h1.card-title="Lista de compras"
    %table.highlight
      %thead
        %tr
          %th= "Ticket"
          %th= "Placa"
          %th= "Customer"
          %th= "Remaining"
      %tbody
        - @activations.each do |activation|
          %tr
            %td= "#{activation.ticket.name} (#{number_to_currency(activation.ticket.price, unit: 'R$ ', separator: ',', delimiter: '')})"
            %td= activation.plate_id ? activation.plate.code : ''
            %td= activation.customer.email
            %td= activation.remaining()
            %td
              = link_to content_tag(:i, "visibility", :class => "material-icons"), admin_activation_path(activation), class: "btn white-text waves-effect waves-dark", title: t("general.show")
              = link_to content_tag(:i, "create", :class => "material-icons"), edit_admin_activation_path(activation), class: "btn white-text waves-effect waves-dark", title: t("general.edit")
              = link_to content_tag(:i, "delete", :class => "material-icons"), [:admin, activation], :method => :delete, :data => { :confirm => t("general.are_you_sure") }, class: "btn red white-text waves-effect waves-dark", title: t("general.destroy")

    .col.s12
      %br
      = link_to content_tag(:i, "add", :class => "material-icons"), new_admin_activation_path, class: "btn white-text waves-effect waves-dark", title: t("general.new")
      = will_paginate @activations

app/views/admin/activations/new.html.haml
= render 'form'

app/views/admin/activations/show.html.haml
%p#notice= notice

.row
  .col.s12.m10.offset-m1.l8.offset-l2.card-panel
    %fieldset.center
      %legend= "Ativação"
      .left-align
        %p= "ID: #{@activation.id}"
        %p= "Placa: #{@activation.plate.code}"
        %p= "Ticket: #{@activation.ticket.name}"
        %p= "Cliente: #{@activation.customer.name} (#{@activation.customer.email})"
        %p= "Restante: #{@activation.remaining}"
        .actions
          = link_to t("general.back"), :back, class: "btn white-text waves-effect waves-dark", title: t("general.back")
          = link_to t("general.edit"), edit_admin_customer_path(@activation), class: "btn white-text waves-effect waves-dark", title: t("general.edit")
          = link_to t("general.destroy"), [:admin, @activation], :method => :delete, :data => { :confirm => t("general.are_you_sure") }, class: "btn red white-text waves-effect waves-dark", title: t("general.destroy")