config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'

  namespace :admin do
    get '', to: 'home#index', as: '/' 

    resources :tickets
    resources :customers
    resources :activations
    resources :plates
    resources :penalties do
      get '/payment' => 'penalties#payment', as: :pay
    end
    resources :purchases
    resources :agents
    resources :penalty_payments, only: [:create, :destroy]

    authenticated :user do
      devise_scope :user do
        root to: 'admin/home#index', as: :root
      end
    end

    unauthenticated do
      devise_scope :user do
        root to: 'admin/sessions#new', as: :unauthenticated_root
      end
    end

    devise_for :users, controllers: {
      sessions: 'admin/sessions',
      registrations: 'admin/registrations',
      passwords: 'admin/passwords'
    }
  end

  namespace :api do
    namespace :v1 do
      resources :customers, only: [:index, :create, :show, :update, :destroy]
      resources :agents, only: [:index, :create, :show, :update, :destroy]
      resources :tickets, only: [:index, :create, :show, :update, :destroy]
      resources :activations, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get 'last_activation' => 'activations#last_activation', as: :last_activation
          get ':plate_code/last_activations' => 'activations#last_activations', as: :last_activations
          get ':customer_id' => 'activations#customer', as: :customer
        end
      end
      resources :penalties, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get '/plate/:plate_id' => 'penalties#plate', as: :plate
          get '/customer/' => 'penalties#customer', as: :customer
          get '/agent/' => 'penalties#agent', as: :agent
          post '/payment' => 'penalties#payment', as: :payment
        end
      end
      resources :purchases, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get '/customer/' => 'purchases#customer', as: :customer
        end
      end
      
      resources :plates, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get '/customer/' => 'plates#customer', as: :customer
        end
      end

      devise_scope :customer do
        resources :sessions, only: [:create]
        resources :registrations, only: [:create, :update]
      end

      devise_scope :agents do
        resources :sessions, only: [:create]
        resources :registrations, only: [:create, :update]
      end
    end
  end

  

end

app/models/penalty.rb
class Penalty < ActiveRecord::Base
  belongs_to :plate
  belongs_to :agent
  has_one :penalty_payment

  before_create :generate_limit

	def generate_limit
    self.limit = DateTime.now + 7.days
	end
end

app/controllers/admin/penalties_controller.rb
class Admin::PenaltiesController < Admin::AdminController
  before_action :set_penalty, only: [:show, :edit, :update, :destroy]

  # GET /penalties
  # GET /penalties.json
  def index
    @penalties = Penalty.all
  end

  # GET /penalties/1
  # GET /penalties/1.json
  def show
  end

  # GET /penalties/new
  def new
    @penalty = Penalty.new
  end

  # GET /penalties/1/payment
  def payment
    # render json: params
    @penalty = Penalty.find(params[:penalty_id])
    @penalty_payment = PenaltyPayment.new
  end

  # GET /penalties/1/edit
  def edit
  end

  # POST /penalties
  # POST /penalties.json
  def create
    @penalty = Penalty.new(penalty_params)

    respond_to do |format|
      if @penalty.save
        format.html { redirect_to [:admin, @penalty], notice: 'Penalty was successfully created.' }
        format.json { render :show, status: :created, location: @penalty }
      else
        format.html { render :new }
        format.json { render json: @penalty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /penalties/1
  # PATCH/PUT /penalties/1.json
  def update
    respond_to do |format|
      if @penalty.update(penalty_params)
        format.html { redirect_to [:admin, @penalty], notice: 'Penalty was successfully updated.' }
        format.json { render :show, status: :ok, location: @penalty }
      else
        format.html { render :edit }
        format.json { render json: @penalty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /penalties/1
  # DELETE /penalties/1.json
  def destroy
    @penalty.destroy
    respond_to do |format|
      format.html { redirect_to admin_penalties_url, notice: 'Penalty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_penalty
      @penalty = Penalty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def penalty_params
      params.require(:penalty).permit(:description, :value, :plate_id, :agent_id, :limit)
    end
end

app/controllers/api/v1/penalties_controller.rb
class Api::V1::PenaltiesController < Api::V1::BaseController
  include ActiveHashRelation

  def index
    penalties = Penalty.all

    penalties = apply_filters(penalties, params)

    render(
      json: ActiveModel::Serializer::CollectionSerializer.new(
        penalties,
        serializer: Api::V1::PenaltySerializer,
        root: 'penalties',
      )
    )
  end
  
  def show
    penalty = Penalty.find(params[:id])

    render json: Api::V1::PenaltySerializer.new(penalty).to_json
  end

  def customer
    return invalid_user unless @current_customer

    penalties = []

    plates = @current_customer.plates

    # render json: plates

    plates.each do |plate|
      platePenalties = plate.penalties
      platePenalties.each do |platePenalty|
        penalties << platePenalty
      end
    end

    render(
      json: ActiveModel::Serializer::CollectionSerializer.new(
        penalties,
        serializer: Api::V1::PenaltySerializer,
        root: 'penalties',
      )
    )
  end

  def agent
    return invalid_user unless @current_agent

    penalties = @current_agent.penalties.order(id: :desc)

    render(
      json: ActiveModel::Serializer::CollectionSerializer.new(
        penalties,
        serializer: Api::V1::PenaltySerializer,
        root: 'penalties',
      )
    )
  end

  def plate
    penalties = Penalty.where(params[:plate_id]).order(id: :desc)

    render(
      json: ActiveModel::Serializer::CollectionSerializer.new(
        penalties,
        serializer: Api::V1::PenaltySerializer,
        root: 'penalties',
      )
    )
  end

  # POST /penalties
  # POST /penalties.json
  def create

    # Precisa receber e fazer validação de token para verificar se corresponde ao customer_id

    return invalid_user unless @current_agent

    plate = Plate.find_by(code: params[:plate_code])
    return api_error unless plate

    @penalty = Penalty.new(penalty_params)

    @penalty.plate = plate;
    @penalty.agent = @current_agent

    if @penalty.save
      render json: Api::V1::PenaltySerializer.new(@penalty).to_json, status: 200
    else
      render json: @penalty.errors, status: 422
    end
  end

  # POST /penalties
  # POST /penalties.json
  def payment

    # Precisa receber e fazer validação de token para verificar se corresponde ao customer_id

    return invalid_user unless @current_customer

    # render json: params

    penalty = Penalty.find(params[:penalty_id])
    return api_error unless penalty

    # render json: penalty

    @penalty_payment = PenaltyPayment.new()

    if(!penalty.penalty_payment.nil?)
      render json: {errors:["Esta multa já foi paga."]}, status: 422
    elsif(@current_customer.cash < penalty.value)
      render json: {errors:["Saldo insuficiente."]}, status: 422
    elsif(penalty.limit < DateTime.now)
      render json: {errors:["Limite para pagamento expirado."]}, status: 422
    # elsif(@penalty_payment.value.to_s != params[:penalty_id])
      # render json: {payment_value:["Valor do pagamento precisa ser o mesmo valor da multa."]}, status: 422
    else

      @penalty_payment.value = penalty.value
      @penalty_payment.penalty = penalty

      if @penalty_payment.save

        newcash = @current_customer.cash - @penalty_payment.value
        @current_customer.cash = newcash
        @current_customer.save

        # render json: @penalty_payment, status: 200
        render json: Api::V1::PenaltySerializer.new(penalty).to_json, status: 200
      else
        render json: @penalty_payment.errors, status: 422
      end
    end
  end

  def cancelPayment

    @plate = Plate.find(params[:id])

    return invalid_customer unless @current_customer

    if(@current_customer.plates.include?(@plate))
      if(@current_customer.plates.delete(@plate))
        render json: {:flash => ["Placa excluída com sucesso."]}, status: 200
      else
        render json: {errors:{plate:["Não foi possível excluir a placa."]}}, status: 422
      end
    else
      render json: {errors:{plate:["Não foi possível excluir a placa."]}}, status: 422
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_penalty
      @penalty = Penalty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def penalty_params
      params.require(:penalty).permit(:description, :value, :plate_id)
    end
end

app/helpers/penalties_helper.rb
module PenaltiesHelper
end

app/views/admin/penalties/_form.html.haml
= simple_form_for([:admin, @penalty]) do |f|
  = f.error_notification
  .row
    .col.s8.offset-s2.card-panel
      %fieldset.center
        %legend= @penalty.new_record? ? 'Nova Multa' : 'Editar Multa'
        .input-field-2
          = f.input :description
        .input-field-2
          = f.input :value
        %div
          = f.input :limit
        .input-field-2
          = f.association :plate, :collection => Plate.all.collect {|p| [p.code, p.id]}
        .input-field-2
          = f.association :agent, :collection => Agent.all.collect {|a| [a.email, a.id]}

        = f.button :submit, input_html: {class: "btn waves-effect waves-light"}

        = link_to t("general.back"), :back, class: "btn white-text waves-effect waves-dark", title: t("general.back")

app/views/admin/penalties/edit.html.haml
= render 'form'

app/views/admin/penalties/index.html.haml
.row
  .card-panel.col.s12
    %h1.card-title="Lista de Multas"
    %table.highlight
      %thead
        %tr
          %th= "ID"
          %th= "Valor"
          %th= "Placa"
          %th= "Agente"
          %th= "Limite"
          %th= "Pago?"
          %th= t("general.actions")
      %tbody
        - @penalties.each do |penalty|
          %tr
            %td= penalty.id
            %td= penalty.value
            %td= penalty.plate.code
            %td= penalty.agent.email
            %td= penalty.limit ? penalty.limit.strftime("%d/%m/%Y %H:%M:%S") : ""
            %td
              %i.material-icons= penalty.penalty_payment ? "done" : "close"
            %td
              - if(penalty.penalty_payment)
                = link_to content_tag(:i, "money_off", :class => "material-icons"), [:admin, penalty.penalty_payment], :method => :delete, :data => { :confirm => t("general.are_you_sure") }, class: "btn red white-text waves-effect waves-dark", title: t("general.destroy")
              - else
                = link_to content_tag(:i, "attach_money", :class => "material-icons"), admin_penalty_pay_path(penalty), class: "btn white-text waves-effect waves-dark", title: t("general.show")
              = link_to content_tag(:i, "visibility", :class => "material-icons"), admin_penalty_path(penalty), class: "btn white-text waves-effect waves-dark", title: t("general.show")
              = link_to content_tag(:i, "create", :class => "material-icons"), edit_admin_penalty_path(penalty), class: "btn white-text waves-effect waves-dark", title: t("general.edit")
              = link_to content_tag(:i, "delete", :class => "material-icons"), [:admin, penalty], :method => :delete, :data => { :confirm => t("general.are_you_sure") }, class: "btn red white-text waves-effect waves-dark", title: t("general.destroy")
              
    .col.s12
      %br
      = link_to content_tag(:i, "add", :class => "material-icons"), new_admin_penalty_path, class: "btn white-text waves-effect waves-dark", title: t("general.new")
      / = will_paginate @penalties

app/views/admin/penalties/new.html.haml
= render 'form'

app/views/admin/penalties/payment.html.haml
= simple_form_for([:admin, @penalty_payment]) do |f|
  = f.error_notification
  .row
    .col.s8.offset-s2.card-panel
      %fieldset.center
        %legend= @penalty_payment.new_record? ? 'Novo Pagamento de Multa' : 'Editar Pagamento de Multa'
        .input-field-2
          = f.input :value, input_html: {value: @penalty.value}
        .input-field-2
          = f.input :penalty_id, input_html: {value: @penalty.id}
        .input-field-2
          = f.association :customer, :collection => Customer.all.collect {|c| [c.email, c.id]}   

        = f.button :submit, input_html: {class: "btn waves-effect waves-light"}

        = link_to t("general.back"), :back, class: "btn white-text waves-effect waves-dark", title: t("general.back")

app/views/admin/penalties/show.html.haml
%p#notice= notice

.row
  .col.s12.m10.offset-m1.l8.offset-l2.card-panel
    %fieldset.center
      %legend= "Multa"
      .left-align
        %p= "ID: #{@penalty.id}"
        %p= "Descrição: #{@penalty.description}"
        %p= "Valor: #{@penalty.value}"
        %p= "Placa: #{@penalty.plate.code}"
        %p= "Limite: #{@penalty.limit ? @penalty.limit.strftime('%d/%m/%Y %H:%M:%S') : ''}"
        %p= "Pago?: #{@penalty.penalty_payment ? 'sim' : 'não'}"
        .actions
          = link_to t("general.back"), :back, class: "btn white-text waves-effect waves-dark", title: t("general.back")
          = link_to t("general.edit"), edit_admin_penalty_path(@penalty), class: "btn white-text waves-effect waves-dark", title: t("general.edit")
          = link_to t("general.destroy"), [:admin, @penalty], :method => :delete, :data => { :confirm => t("general.are_you_sure") }, class: "btn red white-text waves-effect waves-dark", title: t("general.destroy")