config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'

  namespace :admin do
    get '', to: 'home#index', as: '/' 

    resources :tickets
    resources :customers
    resources :activations
    resources :plates
    resources :penalties do
      get '/payment' => 'penalties#payment', as: :pay
    end
    resources :purchases
    resources :agents
    resources :penalty_payments, only: [:create, :destroy]

    authenticated :user do
      devise_scope :user do
        root to: 'admin/home#index', as: :root
      end
    end

    unauthenticated do
      devise_scope :user do
        root to: 'admin/sessions#new', as: :unauthenticated_root
      end
    end

    devise_for :users, controllers: {
      sessions: 'admin/sessions',
      registrations: 'admin/registrations',
      passwords: 'admin/passwords'
    }
  end

  namespace :api do
    namespace :v1 do
      resources :customers, only: [:index, :create, :show, :update, :destroy]
      resources :agents, only: [:index, :create, :show, :update, :destroy]
      resources :tickets, only: [:index, :create, :show, :update, :destroy]
      resources :activations, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get 'last_activation' => 'activations#last_activation', as: :last_activation
          get ':plate_code/last_activations' => 'activations#last_activations', as: :last_activations
          get ':customer_id' => 'activations#customer', as: :customer
        end
      end
      resources :penalties, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get '/plate/:plate_id' => 'penalties#plate', as: :plate
          get '/customer/' => 'penalties#customer', as: :customer
          get '/agent/' => 'penalties#agent', as: :agent
          post '/payment' => 'penalties#payment', as: :payment
        end
      end
      resources :purchases, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get '/customer/' => 'purchases#customer', as: :customer
        end
      end
      
      resources :plates, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get '/customer/' => 'plates#customer', as: :customer
        end
      end

      devise_scope :customer do
        resources :sessions, only: [:create]
        resources :registrations, only: [:create, :update]
      end

      devise_scope :agents do
        resources :sessions, only: [:create]
        resources :registrations, only: [:create, :update]
      end
    end
  end

  

end

app/models/plate.rb
class Plate < ActiveRecord::Base
	validates :code, presence: true, allow_blank: false, length: { is: 8 }
	has_many :activations
	has_many :penalties
	has_and_belongs_to_many :customers, :uniq => true
end

app/controllers/admin/plates_controller.rb
class Admin::PlatesController < ApplicationController
  before_action :set_plate, only: [:show, :edit, :update, :destroy]

  # GET /admin/plates
  # GET /admin/plates.json
  def index
    @plates = Plate.all.order(id: :desc)
  end

  # GET /admin/plates/1
  # GET /admin/plates/1.json
  def show
  end

  # GET /admin/plates/new
  def new
    @plate = Plate.new
  end

  # GET /admin/plates/1/edit
  def edit
  end

  # POST /admin/plates
  # POST /admin/plates.json
  def create
    @plate = Plate.new(plate_params)

    respond_to do |format|
      if @plate.save
        format.html { redirect_to [:admin, @plate], notice: 'Plate was successfully created.' }
        format.json { render :show, status: :created, location: @plate }
      else
        format.html { render :new }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/plates/1
  # PATCH/PUT /admin/plates/1.json
  def update
    respond_to do |format|
      if @plate.update(plate_params)
        format.html { redirect_to [:admin, @plate], notice: 'Plate was successfully updated.' }
        format.json { render :show, status: :ok, location: @plate }
      else
        format.html { render :edit }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/plates/1
  # DELETE /admin/plates/1.json
  def destroy
    @plate.destroy
    respond_to do |format|
      format.html { redirect_to admin_plates_url, notice: 'Plate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plate
      @plate = Plate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plate_params
      params.require(:plate).permit(:code)
    end
end

app/controllers/api/v1/plates_controller.rb
class Api::V1::PlatesController < Api::V1::BaseController
  include ActiveHashRelation

  def index
    plates = Plate.all

    plates = apply_filters(plates, params)

    render(
      json: ActiveModel::Serializer::CollectionSerializer.new(
        plates,
        serializer: Api::V1::PlateSerializer,
        root: 'plates',
      )
    )
  end

  def customer

    return invalid_customer unless @current_customer

    plates = @current_customer.plates

    render(
      json: ActiveModel::Serializer::CollectionSerializer.new(
        plates,
        serializer: Api::V1::PlateSerializer,
        root: 'plates',
      )
    )
  end
  
  def show
    plate = Plate.find(params[:id])

    render json: Api::V1::PlateSerializer.new(plate).to_json
  end

  # POST /plates
  # POST /plates.json
  def create

    @plate = Plate.new(plate_params)

    return invalid_customer unless @current_customer

    current_plate = Plate.find_by(code: @plate.code)

    # render json: !current_plate

    if !current_plate
      if @plate.save
        current_plate = @plate
      else
        render json: {errors: @plate.errors}, status: 422
      end
    end

    if(current_plate)
      if (current_plate.customers.include?(@current_customer))
        render json: {errors:{plate: ["Esta placa já está cadastrada."]}}, status: 422
      elsif (current_plate.customers << @current_customer)
        render json: Api::V1::PlateSerializer.new(current_plate).to_json, status: 200
      else
        render json: {errors:{plate: ["Não foi possível cadastrar a placa."]}}, status: 422
      end
    end

  end

  # DELETE /admin/plates/1
  # DELETE /admin/plates/1.json
  def destroy

    @plate = Plate.find(params[:id])

    return invalid_customer unless @current_customer

    if(@current_customer.plates.include?(@plate))
      if(@current_customer.plates.delete(@plate))
        render json: {:flash => ["Placa excluída com sucesso."]}, status: 200
      else
        render json: {errors:{plate:["Não foi possível excluir a placa."]}}, status: 422
      end
    else
      render json: {errors:{plate:["Não foi possível excluir a placa."]}}, status: 422
    end
    
  end

  private

    def invalid_customer
      warden.custom_failure!
      render(
        json: {:errors => ["Usuário não encontrado."]},
        status: 401
      )
    end

    def invalid_value
      warden.custom_failure!
      render(
        json: {:errors => ["Valor incorreto."]},
        status: 401
      )
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_plate
      @plate = Plate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plate_params
      params.require(:plate).permit(:code)
    end
end

app/helpers/admin/plates_helper.rb
module Admin::PlatesHelper
end

app/views/admin/plates/_form.html.haml
= simple_form_for([:admin, @plate]) do |f|
  = f.error_notification
  .row
    .col.s8.offset-s2.card-panel
      %fieldset.center
        %legend= @plate.new_record? ? 'Nova Placa' : 'Editar Placa'
        .input-field-2
          = f.input :code

    

        = f.button :submit, input_html: {class: "btn waves-effect waves-light"}

        = link_to t("general.back"), :back, class: "btn white-text waves-effect waves-dark", title: t("general.back")

app/views/admin/plates/edit.html.haml
= render 'form'

app/views/admin/plates/index.html.haml
.row
  .card-panel.col.s12
    %h1.card-title="Lista de placas"
    %table.highlight
      %thead
        %tr
          %th= "ID"
          %th= "Código"
          %th= "Nº de clientes"
          %th= t("general.actions")

      %tbody
        - @plates.each do |plate|
          %tr
            %td= plate.id
            %td= plate.code
            %td= plate.customers ? plate.customers.count : 0
            %td
              = link_to content_tag(:i, "visibility", :class => "material-icons"), admin_plate_path(plate), class: "btn white-text waves-effect waves-dark", title: t("general.show")
              = link_to content_tag(:i, "create", :class => "material-icons"), edit_admin_plate_path(plate), class: "btn white-text waves-effect waves-dark", title: t("general.edit")
              = link_to content_tag(:i, "delete", :class => "material-icons"), [:admin, plate], :method => :delete, :data => { :confirm => t("general.are_you_sure") }, class: "btn red white-text waves-effect waves-dark", title: t("general.destroy")


= link_to 'New Plate', new_admin_plate_path

app/views/admin/plates/new.html.haml
= render 'form'

app/views/admin/plates/show.html.haml
%p#notice= notice

.row
	.col.s12.m10.offset-m1.l8.offset-l2.card-panel
		%fieldset.center
			%legend= "Informações da Placa"
			.left-align
				%p= "Código: #{@plate.code}"
				%p= "Clientes vinculados:"
				%ul
					- @plate.customers.each do |customer|
						%li= customer.email

			= link_to 'Edit', edit_admin_plate_path(@plate)
			\|
			= link_to 'Back', admin_plates_path