config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'

  namespace :admin do
    get '', to: 'home#index', as: '/' 

    resources :tickets
    resources :customers
    resources :activations
    resources :plates
    resources :penalties do
      get '/payment' => 'penalties#payment', as: :pay
    end
    resources :purchases
    resources :agents
    resources :penalty_payments, only: [:create, :destroy]

    authenticated :user do
      devise_scope :user do
        root to: 'admin/home#index', as: :root
      end
    end

    unauthenticated do
      devise_scope :user do
        root to: 'admin/sessions#new', as: :unauthenticated_root
      end
    end

    devise_for :users, controllers: {
      sessions: 'admin/sessions',
      registrations: 'admin/registrations',
      passwords: 'admin/passwords'
    }
  end

  namespace :api do
    namespace :v1 do
      resources :customers, only: [:index, :create, :show, :update, :destroy]
      resources :agents, only: [:index, :create, :show, :update, :destroy]
      resources :tickets, only: [:index, :create, :show, :update, :destroy]
      resources :activations, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get 'last_activation' => 'activations#last_activation', as: :last_activation
          get ':plate_code/last_activations' => 'activations#last_activations', as: :last_activations
          get ':customer_id' => 'activations#customer', as: :customer
        end
      end
      resources :penalties, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get '/plate/:plate_id' => 'penalties#plate', as: :plate
          get '/customer/' => 'penalties#customer', as: :customer
          get '/agent/' => 'penalties#agent', as: :agent
          post '/payment' => 'penalties#payment', as: :payment
        end
      end
      resources :purchases, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get '/customer/' => 'purchases#customer', as: :customer
        end
      end
      
      resources :plates, only: [:index, :create, :show, :update, :destroy] do
        collection do
          get '/customer/' => 'plates#customer', as: :customer
        end
      end

      devise_scope :customer do
        resources :sessions, only: [:create]
        resources :registrations, only: [:create, :update]
      end

      devise_scope :agents do
        resources :sessions, only: [:create]
        resources :registrations, only: [:create, :update]
      end
    end
  end

  

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	#Enum
  enum status: {  ativo: 0 , finalizado: 1}
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::AdminController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.paginate(:page => params[:page])
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to [:admin, @ticket], notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to [:admin, @ticket], notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to admin_tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :description, :price, :duration)
    end
end

app/controllers/api/v1/tickets_controller.rb
class Api::V1::TicketsController < Api::V1::BaseController
  include ActiveHashRelation

  def index
    tickets = Ticket.all

    tickets = apply_filters(tickets, params)

    render(
      json: ActiveModel::Serializer::CollectionSerializer.new(
        tickets,
        serializer: Api::V1::TicketSerializer,
        root: 'tickets',
      )
    )
  end
  
  def show
    ticket = Ticket.find(params[:id])

    render(json: Api::V1::TicketSerializer.new(ticket).to_json)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/tickets/_form.html.haml
= simple_form_for([:admin, @ticket]) do |f|
  = f.error_notification
  .row
    .col.s8.offset-s2.card-panel
      %fieldset.center
        %legend= @ticket.new_record? ? 'Novo Ticket' : 'Editar Ticket'
        .input-field-2
          = f.input :name
        .input-field-2
          = f.input :description, input_html: {class: "materialize-textarea"}
        .input-field-2
          = f.input :price
        .input-field-2
          = f.input :duration

    

        = f.button :submit, input_html: {class: "btn waves-effect waves-light"}

        = link_to t("general.back"), :back, class: "btn white-text waves-effect waves-dark", title: t("general.back")

app/views/admin/tickets/edit.html.haml
= render 'form'

app/views/admin/tickets/index.html.haml
.row
  .card-panel.col.s12
    %h1.card-title="Lista de tickets"
    %table.highlight
      %thead
        %tr
          %th= "ID"
          %th= "Name"
          %th= "Valor"
          %th= "Duração"
          %th= t("general.actions")

      %tbody
        - @tickets.each do |ticket|
          %tr
            %td= ticket.id
            %td= ticket.name
            %td= number_to_currency(ticket.price, unit: "R$ ", separator: ",", delimiter: "")
            %td= ticket.duration
            %td
              = link_to content_tag(:i, "visibility", :class => "material-icons"), admin_ticket_path(ticket), class: "btn white-text waves-effect waves-dark", title: t("general.show")
              = link_to content_tag(:i, "create", :class => "material-icons"), edit_admin_ticket_path(ticket), class: "btn white-text waves-effect waves-dark", title: t("general.edit")
              = link_to content_tag(:i, "delete", :class => "material-icons"), [:admin, ticket], :method => :delete, :data => { :confirm => t("general.are_you_sure") }, class: "btn red white-text waves-effect waves-dark", title: t("general.destroy")

    .col.s12
      %br
      = link_to content_tag(:i, "add", :class => "material-icons"), new_admin_ticket_path, class: "btn white-text waves-effect waves-dark", title: t("general.new")
      = will_paginate @tickets

app/views/admin/tickets/new.html.haml
= render 'form'

app/views/admin/tickets/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_ticket_path(@ticket)
\|
= link_to 'Back', admin_tickets_path

%p#notice= notice

.row
  .col.s12.m10.offset-m1.l8.offset-l2.card-panel
    %fieldset.center
      %legend= "Ticket"
      .left-align
        %p= "ID: #{@ticket.id}"
        %p= "Nome: #{@ticket.name}"
        %p= "Valor: #{@ticket.price}"
        %p= "Duração: #{@ticket.duration}"
        .actions
          = link_to t("general.back"), :back, class: "btn white-text waves-effect waves-dark", title: t("general.back")
          = link_to t("general.edit"), edit_admin_ticket_path(@ticket), class: "btn white-text waves-effect waves-dark", title: t("general.edit")
          = link_to t("general.destroy"), [:admin, @ticket], :method => :delete, :data => { :confirm => t("general.are_you_sure") }, class: "btn red white-text waves-effect waves-dark", title: t("general.destroy")